name: almato_scanner
description: A flutter plugin to detect edges of objects, scan paper, detect corner, detect rectangle. It allows cropping of the detected object image and returns the path of the cropped image.
version: 1.0.0
homepage: https://github.com/anthonycuervo23/almato_edge_detection

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.sample.almatoscanner
        pluginClass: AlmatoScannerPlugin
      ios:
        pluginClass: AlmatoScannerPlugin

